---
title: "Final Data Science Project Proposal"
author: "Adam Brandt, Allan Juarez, John King, Lisa McDaniel, Colin Willenborg "
date: "10/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## **DS 202 Fall 2020**
## **Team 2:**	

<font size = "4">
Adam Brandt, Allan Juarez, John King, Lisa McDaniel, Colin Willenborg
		
## **Data Source:**

<font size = "4"> https://iowadot.gov/program_management/FINAL_2021-2025_5YrProg.pdf

## **Dataset Overview:**
The 2021-2025 five-year plan is prepared by the Iowa Department of Transportation (Iowa DOT) and documents the projects planned on an annual basis for a period of five years, in this case 2021-2025.  It includes project location, county, work type, route and cost estimate.  The document is updated annually by removing completed projects, introducing new projects, revising project schedules and costs and rescheduling projects as needed.  It is annually approved by the Iowa DOT commission and provides transparency by being made available to the public.  Information in the five-year plan assists the Iowa DOT, local public agencies and the federal government in developing a budget, identify needs, project status, project length, documentation requirements, and staffing needs.  The document also makes it easier for organizations to compare estimated project costs with actual project costs, and track project costs/status over the years, across the state/county and by project.

It should be noted that only the information for the Highway Program (pages 50 – 94) is being used for this project.  The five-year plan is originally created as a pdf and exported to an excel spreadsheet.  The conversion was a bit messy so quality assurance (QA) was done to ensure that project costs were correct and in the correct year.  Several columns were added to the dataset including Iowa DOT District, county latitude and longitude and projects reschedule in case the Highway Trust Funds becomes insolvent. 

## **Exploratory Analysis:** What questions can be answered from the dataset?

•	Type, number, Iowa DOT District, County, route, location and estimated costs of projects planned between 2021 – 2025.  Where is the money going and how much? - Allan

•	What work types are associated with interchanges?  Costs? What routes are interchanges being proposed on?  - John

•	Projects < $50 million, projects > $50 million & < $100 million, major projects > $100.  What is the most expenvie project in each District?  The least expensive?  - Adam

•	Project types and costs between Iowa DOT Districts and years. - Colin 

•	How many bridges are being constructed, replaced, reconstructed, maintained or   preserved? CUlverts? What is the average cost by type of construction?  Is there a difference in cost between Districts? - Lisa

•	How many miles of pavement are being constructed, replaced, reconstructed, maintained or preserved? What is the cost per mile, by type of construction?  Is there a difference in cost per mile between Districts? - Lisa
